job_categories = [
    {"id": "back-end-engineer", "name": "後端工程師"},
    {"id": "front-end-engineer", "name": "前端工程師"},
    {"id": "software-engineer", "name": "軟體工程師"},
    {"id": "full-stack-development", "name": "全端工程師"},
    {"id": "blockchain-platform-engineer", "name": "區塊鏈工程師"},
    {"id": "qa-test-engineer", "name": "軟體測試工程師"},
    {"id": "devops-system-admin", "name": "DevOps工程師"},
    {"id": "data-engineer", "name": "資料工程師"},
    {"id": "python-developer", "name": "軟體工程師"},
    {"id": "data-scientist", "name": "資料科學家"},
    {"id": "ios-developer", "name": "APP工程師"},
    {"id": "java-developer", "name": "軟體工程師"},
    {"id": "research-r-d", "name": "研發工程師"},
    {"id": "web-developer", "name": "網站開發人員"},
    {"id": "android-developer", "name": "APP工程師"},
    {"id": "machine-learning-engineer", "name": "機器學習工程師"},
    {"id": "php-developer", "name": "軟體工程師"},
    {"id": "ruby-on-rails-developer", "name": "軟體工程師"},
    {"id": "system-architecture", "name": "系統工程師"},
    {"id": "c-c-developer", "name": "軟體工程師"},
    {"id": "big-data-engineer", "name": "資料工程師"},
    {"id": "node-js-developer", "name": "軟體工程師"},
    {"id": "system-analyst", "name": "系統分析師"},
    {"id": "development-manager", "name": "專案/技術主管"},
    {"id": "database", "name": "資料庫管理人員"},
    {"id": "chief-technology-officer", "name": "專案/技術主管"},
    {"id": "app-developer", "name": "APP工程師"},
    {"id": "net-developer", "name": "軟體工程師"},
    {"id": "technical-manager", "name": "專案/技術主管"},
]

job_type_dict = {
    "full_time": "全職",
    "part_time": "兼職",
    "internship": "實習生",
    "contract": "約聘",
    "freelance": "接案",
}

salary_type_dict = {
    "per_month": "月薪",
    "per_hour": "時薪",
    "per_year": "年薪",
    "negotiable": "面議",
    "piece_rate_pay": "論件計酬",
}
